var indObj= {
    concatus: 'Hubungi kami',
    aboutus: 'Tentang kami',
    home: 'Halaman utama',
    list: 'Klasifikasi',
    classlist:'Daftar kategori',
    outfloor: 'Tidak ada lagi',
    hotgoods: 'Baru saja dikirimkan barang',
    carriage: 'Biaya ongkir',  //运费
    inventory: 'Sisa stok', //库存
    select: 'Pilih', //选择
    selected: 'Telah dipilih', //已选
    goodsDetails: 'Parameter produk',
    comment: 'komentar',
    nomore: 'Tidak ada lagi',
    shopCart: 'Daftar belanja',
    store: 'Mall', //店铺
    addCart: 'tambah ke keranjang',
    buy: 'Segera pesan',//立即购买
    ok: 'Konfirm',
    buyNum: 'Jumlah pesanan', //购买数量
    message: 'Tinggalkan pesan', //留言
    storeenter: 'Masuk ke mall',
    stock: 'Sudah terjual ',
    official: 'The official',
    messagePlaceholder: 'Silakan masukkan teks anda',
    serveError: 'Galat server, pengiriman data gagal',
    successAdd: 'Berhasil ditambahkan',
    coupoCode: 'Bantuan yards',
    coupoCodeholder: 'Kode promo, silakan',
    coupoCodeSend: 'Verifikasi',
    couponerr: 'Kode promo tidak valid',
    couponmoney: 'Jumlah bantuan',
    couponUn: 'Preferential terms not met',
    account: 'Penyelesaian',
    total: 'Jumlah',
    back: 'Kembali',
    clearCart: 'Hapuskan daftar',
    clear: 'Hapuskan',
    payOnDelivery: 'Cara pembayaran COD', //货到付款
    name: 'Nama',
    nameholder: 'Masukan nama lengkap',
    phoneNumber: 'Nomor telpon',
    phoneNumberholder: 'Masukan nomor telpon yg aktif',
    email: 'Alamat email',
    emailholder: 'Masukan alamat email',
    province: 'Kota provinsi kabupaten',
    provinces: 'Provinsi',
    crity: 'Kota',
    county: 'Kabupaten',
    provinceholder: 'Masukan Kota provinsi kabupaten',
    address: 'Alamat lengkap',
    addressholder: 'Masukan alamat lengkap',
    zipCode: 'P. M. A.',
    zipCodeholder: 'Kode pos, silakan',
    zipCodeholder1: 'Memilih daerah metropolitan pertama',
    messageholder: 'Silakan tinggalkan pesan',
    nameerr: 'Tempat ini tidak boleh kosong',
    errTelephone: 'Tempat ini tidak boleh kosong',
    errTelephone2:'Kesalahan format nomor telepon',
    errShort_address: 'Tempat ini tidak boleh kosong',
    errAddress: 'Tempat ini tidak boleh kosong',
    errEmail: 'Format alamat email salah',
    orderNumber: 'Nomor pesanan:',
    orderTime: 'Waktu pemesanan:',
    ordersuccessful: 'Transaksi  berhasil',
    atLeastOne: 'Pilih setidaknya satu',
    selectGoodsFirst: 'Silakan pilih spesifikasi produk',
    cartnull: 'Daftar belanja Anda kosong!',
    pullingText: 'Tarik ke bawah untuk menyegarkan...',
    lossText: 'Lepaskan untuk menyegarkan...',
    loading: 'Loading...',
    loadSuccess: 'Segarkan dengan sukses',
    errorText:'Permintaan gagal, klik reload',
    confirm: 'Konfirmasi',
    cancel: 'Batalkan',
    score: 'Skor',
    tocomment: 'Untuk berkomentar',
    resgoods: 'Anda mungkin seperti ini lagi',
    sendSucess: 'Kirim berhasil',
    errMessage: 'Komentar tidak boleh kosong',
    justbuy: 'Barusan membeli barang ini !',
    floorPage_1Title: 'Perhatikan',
    floorPage_1_1: 'Hasil penggunaan sebenarnya produk ini ditentukan oleh keadaan pribadi, tidak bisa menjamin semua pengguna dapat menikmati efek promosi.Kalau ada pertanyaan,bisa hubungi kami via layanan pengguna online atau email(',
    floorPage_1_2: '),perusahaan kami memiliki hak interpretasi akhir.',
    floorPage_1_2_1_Html: '<strong>Penyangkalan</strong><p style="color: #ef3470;">Situs ini bukan bagian dari situs Facebook atau Inc. Selain itu, situs ini tidak disetujui Facebook dengan cara apapun. Thefacebook merupakan ciri khas FACEBOOK, Inc.</p>',
    floorPage_2Title: 'Cara penggantian dan pengembalian',
    floorPage_2_1: '1.Alasan pribadi:Dalam 7 hari dari tanggal penerimaan barang dan tidak mempengaruhi penjualan lagi.Silakan hubungi layanan pelanggan online kami atau kirim email ke',
    floorPage_2_2: '. Setelah terima permintaan Anda,bagian layanan pelanggan kami akan mengurus dalam 1-3 hari kerja,ongkos penggantian dan pengembalian dibayarkan oleh pelanggan sendiri.',
    floorPage_2_3: '2.Alasan kualitas:Dalam 7 hari dari tanggal penerimaan barang,silakan kirim email ke bagian layanan pelanggan kami',
    floorPage_2_4: ', bagian layanan pelanggan kami akan mengurus permintaan Anda dalam 1-3 hari kerja,ongkos penggantian dan pengembalian dibayarkan oleh perusahaan kami.',
    floorPage_3Title: 'Alur penggantian dan pengembalian',
    floorPage_3_1: 'Konfirmasi terima barang–minta ganti dan kembali barang–setuju oleh pelayan pelanggan–pelanggan kirim barang –gudang terima dan periksa barang–periksa ganti dan kembali barang –kembali uang/ganti barang',
    floorPage_3_2: 'Silakan isi : Nomor pesanan, nama dan no HP.',
    floorPage_4: 'Fleekfly adalah online mall yang memilih produk dengan sikap yang ketat mengikuti secara konsisten, Menyebar ke seluruh dunia, secara ketat mengontrol asal produk, baik komoditas kerajinan, bahan baku, pakaian, tas dan sepatu, peralatan rumah tangga,  peralatan dapur, olahraga dll. Kami berusaha memberikan produk kualitas terbaik kepada Anda .',

    floorPage_aboutus: 'Fleekfly adalah online mall yang memilih produk dengan sikap yang ketat mengikuti secara konsisten, Menyebar ke seluruh dunia, secara ketat mengontrol asal produk, baik komoditas kerajinan, bahan baku, pakaian, tas dan sepatu, peralatan rumah tangga,  peralatan dapur, olahraga dll. Kami berusaha memberikan produk kualitas terbaik kepada Anda .',
    floorPage_shoping: '<p><span>Garansi pengembalian barang di ydzsac.com hanya berlaku 14 hari kalender sejak tanggal penerimaan. Penghitungan dimulai dari tanggal Anda menerima produk sampai tanggal cap pos yang tertera pada dokumen pengiriman yang Anda kembalikan kepada kami. Barang hanya dapat dikembalikan untuk pengembalian uang jika tidak dibuka, tidak digunakan, dan dalam kondisi dapat dijual kembali dengan semua segel, pengemasan, dan selofan yang tahan terhadap kerusakan.</span></p><br/> <p><span>Harap pastikan bahwa Anda juga mengembalikan hadiah gratis yang terkait dengan item pengembalian Anda atau pesanan terkait. Jika hadiah gratis tidak dikembalikan, maka kami berhak untuk mengurangi nilai hadiah gratis dari pengembalian dana Anda. Kami merekomendasikan foto diambil dari item sebelum mengembalikannya jika Anda khawatir tentang kerusakan selama perjalanan kembali.</span></p><br/> <p><span>Harap dicatat bahwa kami tidak menerima pengembalian untuk produk yang pribadi.Harap dicatat nomor pesanan harus dimasukkan tanpa surat pada bagian akhir.Jika Anda tidak memiliki catatan pengiriman atau faktur,harap sertakan catatan penjelasan yang mengutip nomor pesanan Anda dan alasan pengembalian.</span></p><br/> <p><span>Pengembalian dana Anda akan diproses, setelah dikirim ke gudang kami dan dalam waktu 3 hari kerja setelah kembali ke kami Pengembalian uang bisa memakan waktu hingga 1 minggu untuk ditampilkan di akun Anda; ini disebabkan oleh waktu yang diambil oleh beberapa bank untuk memproses pembayaran.</span></p><br/> <p><span>Kami akan mengembalikan Anda dengan metode pembayaran yang sama dengan yang digunakan untuk membuat pesanan asli (misalnya. Jika Anda telah membayar oleh PayPal, kami akan mengembalikan akun PayPal Anda) Jika Anda belum menerima pengembalian dana setelah waktu ini, silakan hubungi Tim Layanan Pelanggan kami dan kami akan membantu Anda dengan senang .</span></p>',
    floorPage_return: 'Konfirmasi penerimaan — Terapkan untuk pengembalian / pertukaran — Konfirmasi oleh layanan pelanggan-Kirim barang kembali-Dikirim ke gudang — Inspeksi --- Pengembalian Dana / Pertukaran.<br/><br/> Silakan lampirkan dengan No. Pemesanan, No. Kontak, dan nama Pelanggan.<br/><br/>Barang hanya dapat dikembalikan untuk pengembalian uang jika tidak dibuka, tidak digunakan, dan dalam kondisi dapat dijual kembali dengan semua segel, pengemasan, dan selofan yang tahan terhadap kerusakan. Anda harus memberi tahu kami secara tertulis bahwa Anda mengembalikan pembelian Anda dalam 14 hari, mulai hari  hari  Andasetelah menerima produk.<br/><br/>Harap pastikan bahwa Anda juga mengembalikan hadiah gratis yang terkait dengan item pengembalian Anda atau pesanan terkait. Jika hadiah gratis tidak dikembalikan, maka kami berhak untuk mengurangi nilai hadiah gratis dari pengembalian dana Anda. Kami merekomendasikan foto diambil dari item sebelum mengembalikannya jika Anda khawatir tentang kerusakan selama perjalanan kembali.Harap dicatat bahwa kami tidak menerima pengembalian untuk produk yang pribadi.Harap dicatat nomor pesanan harus dimasukkan tanpa surat pada bagian akhir.Jika Anda tidak memiliki catatan pengiriman atau faktur,harap sertakan catatan penjelasan yang mengutip nomor pesanan Anda dan alasan pengembalian.Pengembalian dana Anda akan diproses, setelah dikirim ke gudang kami dan dalam waktu 3 hari kerja setelah kembali ke kami Pengembalian uang bisa memakan waktu hingga 1 minggu untuk ditampilkan di akun Anda; ini disebabkan oleh waktu yang diambil oleh beberapa bank untuk memproses pembayaran.<br/><br/>Kami akan mengembalikan Anda dengan metode pembayaran yang sama dengan yang digunakan untuk membuat pesanan asli (misalnya. Jika Anda telah membayar oleh PayPal, kami akan mengembalikan akun PayPal Anda) Jika Anda belum menerima pengembalian dana setelah waktu ini, silakan hubungi Tim Layanan Pelanggan kami dan kami akan membantu Anda dengan senang .',
    floorPage_privacy: 'Data pribadi apa yang kami kumpulkan tentang Anda?<br><br>Kami mengumpulkan data pribadi dari Anda ketika Anda memberikannya kepada kami secara langsung dan melalui penggunaan Situs oleh Anda. Informasi ini dapat meliputi:<br><br>• Informasi yang Anda berikan kepada kami ketika Anda menggunakan Situs kami (mis. Nama Anda, detail kontak, ulasan produk, dan informasi apa pun yang Anda tambahkan di situs kami);<br><br>• Informasi transaksi dan penagihan, jika Anda melakukan pembelian dari kami atau menggunakan Situs kami (mis. Detail PayPal dan informasi pengiriman);<br><br>• Catatan interaksi Anda dengan kami (misalnya. Jika Anda menghubungi tim layanan pelanggan kami, berinteraksi dengan kami di media sosial);<br><br>• Informasi yang Anda berikan kepada kami ketika Anda mengikuti kompetisi atau berpartisipasi dalam survei;<br><br>• Informasi dikumpulkan secara otomatis, menggunakan cookie dan teknologi pelacakan lainnya.<br><br>Kami akan menggunakan data pribadi ini untuk apa ?<br><br>Bergantung pada bagaimana Anda menggunakan Situs kami, interaksi Anda dengan kami, dan izin yang Anda berikan kepada kami, tujuan kami menggunakan data pribadi Anda meliputi:<br><br>• Untuk memenuhi pesanan Anda<br><br>• Untuk mengelola dan menanggapi pertanyaan atau keluhan apa pun kepada tim layanan pelanggan kami.<br><br>• Untuk meningkatkan dan memelihara Situs, dan memantau penggunaannya.<br><br>• Untuk riset pasar, mis. kami dapat menghubungi Anda untuk umpan balik tentang produk kami.<br><br>• Untuk tujuan keamanan, untuk menyelidiki penipuan dan jika perlu untuk melindungi diri kita sendiri dan pihak ketiga.<br><br>• Untuk mematuhi kewajiban hukum dan peraturan kami.<br><br>Kami mengandalkan dasar hukum berikut, di bawah undang-undang perlindungan data, untuk memproses data pribadi Anda:<br><br>• Karena pemrosesan diperlukan untuk melakukan kontrak dengan Anda, atau mengambil langkah-langkah sebelum menandatangani kontrak dengan Anda (misalnya. Tempat  Anda melakukan pembelian dengan kami, kami menggunakan data pribadi Anda untuk memproses pembayaran dan memenuhi pesanan Anda).<br><br>• Karena kepentingan kami yang sah sebagai penyedia e-commerce untuk mempertahankan dan mempromosikan layanan kami. Kami selalu berusaha memahami lebih banyak tentang pelanggan kami untuk menawarkan produk dan pengalaman pelanggan terbaik.<br><br>Dengan siapa kami berbagi data pribadi ini?<br><br>Kami dapat berbagi informasi dengan lembaga pemerintah atau perusahaan lain yang membantu kami dalam pencegahan atau penyelidikan penipuan. Kami dapat melakukannya ketika:<br><br>• Diijinkan atau diharuskan oleh hukum; atau,<br><br>• Berusaha melindungi atau mencegah penipuan aktual atau potensial atau transaksi tidak sah; atau,<br><br>• Investigasi penipuan yang sudah terjadi. Informasi tidak diberikan kepada perusahaan-perusahaan ini untuk tujuan pemasaran.<br><br>Kami juga dapat mengungkapkan informasi pribadi Anda, tanpa pemberitahuan, jika tindakan tersebut diperlukan untuk:<br><br>• Mematuhi ketentuan hukum atau mematuhi proses hukum yang disajikan di Situs;<br><br>• Melindungi dan mempertahankan hak atau properti Situs;<br><br>• Bertindak dalam keadaan mendesak untuk melindungi keamanan pribadi pengguna Situs.<br><br>Keamanan<br><br>Situs ini memastikan bahwa data dienkripsi ketika meninggalkan Situs. Proses ini melibatkan konversi informasi atau data menjadi kode untuk mencegah akses yang tidak sah. Situs ini mengikuti proses ini dan menggunakan metode aman untuk memastikan perlindungan semua transaksi pembayaran. Metode enkripsi seperti SSL digunakan untuk melindungi data pelanggan saat dalam perjalanan ke dan dari Situs ini melalui saluran komunikasi yang aman.<br><br>Sementara kami melakukan segala daya kami untuk memastikan bahwa data pribadi dilindungi setiap saat dari Situs kami, kami tidak dapat menjamin keamanan dan integritas informasi yang telah dikirim ke Situs kami.<br><br>Cookie<br><br>Situs dapat menggunakan cookie dan teknologi pelacakan tergantung pada fitur yang ditawarkan. Teknologi cookie dan pelacakan berguna untuk mengumpulkan informasi seperti jenis browser dan sistem operasi, melacak jumlah pengunjung ke Situs, dan memahami bagaimana pengunjung menggunakan Situs. Cookie juga dapat membantu menyesuaikan Situs untuk pengunjung. Informasi pribadi tidak dapat dikumpulkan melalui cookie dan teknologi pelacakan lainnya, namun, jika sebelumnya Anda memberikan informasi pengenal pribadi, cookie dapat dikaitkan dengan informasi tersebut. Cookie gabungan dan informasi pelacakan dapat dibagi dengan pihak ketiga.<br><br>Hubungi kami<br><br>Jika Anda memiliki pertanyaan, masalah, atau komentar tentang kebijakan privasi kami, Anda dapat menghubungi kami.',
    floorPage_contact_1: '• Email: <b>',
    floorPage_contact_2: "</b> <br/><br/>Jika Anda memiliki pertanyaan, silakan tinggalkan pesan, Layanan Pelanggan akan menjawab umumnya dalam waktu 24 (hari kerja)jam / 48 (akhir pekan) jam.<br/>Untuk informasi umum, seperti proses pembelian, metode pembayaran, opsi pengiriman atau proses sengketa, silakan merujuk ke halaman Bantuan kami.<br/><br/>Jika Anda memerlukan pertanyaan dengan pesanan terbaru Anda, silakan hubungi Pusat Layanan Pelanggan kami di <b>",
    floorPage_contact_3: '</b><br/><br/>Alamat Perusahaan: 152 Beach Road, # 14-02, Gateway East, Singapura 189721 (Alamat tidak-kembali, jika Anda perlu mendapatkan alamat kembali, silakan hubungi layanan pelanggan kami)' ,

    mainFooter_1:'jaminan',
    mainFooter_1_1:'jika anda tidak menerima barang pengembalian uang sepenuhnya！',
    mainFooter_1_2:'Jika barang yang Anda beli tidak cocok dengan deskripsi，Pengembalian uang penuh ！',
    mainFooter_About:'tentang kami',
    mainFooter_shipping:'ketentuan pengiriman',
    mainFooter_return:'kebijakan retur',
    mainFooter_privacy:'kebijakan pribadi',
    mainFooter_contact:'hubungi kami',
    mainFooter_2:'. All rights reserved',
    buyNow:'Beli Sekarang',
    seek:'cari',
    searchProducts:'cari produk',
    seekErr:'Tidak menemukan hasil produk ',
    seekErr_1:'Harap masukkan kembali permintaan produk!'
}
var flbObj= {
    concatus: 'Contact us',
    aboutus: 'About us',
    home: 'Home',
    list: 'Category',
    classlist:'Category list',
    outfloor: 'No more',
    hotgoods: 'Selling goods',
    carriage: 'Shipping fee',  //运费
    inventory: 'Stock quantity', //库存
    select: 'Select', //选择
    selected: 'The selected',
    goodsDetails: 'Product detail',
    comment: 'Comment',
    nomore: 'No more',
    shopCart: 'Shopping cart',
    store: 'Mall', //店铺
    addCart: 'Add to cart',
    buy: 'Buy',//立即购买
    ok: 'CONFIRM',
    buyNum: 'Quantity', //购买数量
    message: 'Leave word ', //留言
    storeenter: 'Enter the mall',
    official: 'resmi',
    messagePlaceholder: 'Please enter your text',
    serveError: 'Server error, data retrieval failed',
    successAdd: 'Successfully added',
    account: 'Check out',
    total: 'Total',
    back: 'Back',
    clearCart: 'Clear cart',
    clear: 'Clear',
    payOnDelivery: 'Pay on delivery', //货到付款
    name: 'Name',
    nameholder: 'Please input your name',
    phoneNumber: 'Phone Number',
    phoneNumberholder: ' Please input your phone number',
    email: 'Email',
    emailholder: 'Please input your email',
    province: 'Province',
    provinces: 'Province',
    crity: 'Crity',
    county: 'County',
    provinceholder: 'Please input your Province, city and district',
    address: 'Detailed Address',
    addressholder: 'Please input your Detailed Address',
    zipCode: 'Zip code',
    zipCodeholder: 'Please input zip code',
    zipCodeholder1: 'Please choose the provincial area first',
    messageholder: 'Please input your message',
    nameerr: 'Name can’t be blank!',
    errTelephone: 'Phone number can’t be blank!',
    errTelephone2:'Wrong format of phone number!',
    errShort_address: 'Province, city and district can’t be blank!',
    errAddress: 'Full address can’t be blank',
    errEmail: 'Email format can’t be blank!',
    orderNumber: 'Order No:',
    orderTime: 'Order Time:',
    ordersuccessful: 'Order successful',
    atLeastOne: 'Choose at least one',
    selectGoodsFirst: 'Please select the product specification first',
    cartnull: 'Your shopping cart is empty!',
    pullingText: 'Pull down to refresh...',
    lossText: 'Loosen to refresh...',
    loading: 'Loading...',
    loadSuccess: 'Refresh the success',
    errorText:'The request failed, click reload',
    confirm: 'Confirm',
    cancel: 'Cancel',
    score: 'Score',
    tocomment: 'To comment',
    sendSucess: 'Send a success',
    errMessage: 'Comments cannot be empty',
    resgoods: 'You might like these',
    coupoCode: 'Promo code',
    coupoCodeholder: 'Please input your discount code',
    coupoCodeSend: 'Validation',
    couponerr: 'Coupon code invalid',
    stock: 'Already snapped up ',
    couponmoney: 'Discount amount',
    couponUn: 'Kondisi penawaran tidak terpenuhi',
    justbuy: 'Has just bought this item !',
    floorPage_1Title: 'PRIVACY POLICY',
    floorPage_1Html: '<strong> What personal data do we collect about you?</strong><p>We collect personal data from you when you provide it to us directly and through your use of the Site. This information may include:</p><p>•    Information you provide to us when you use our Site (e.g. your name, contact details, product reviews, and any information which you add our site);</p><p>•    Transaction and billing information, if you make any purchases from us or using our Site (e.g. PayPal details and delivery information);</p><p>•    Records of your interactions with us (e.g. if you contact our customer service team, interact with us on social media);</p><p>•    Information you provide us when you enter a competition or participate in a survey;</p><p>•    Information collected automatically, using cookies and other tracking technologies .</p><strong>What do we use this personal data for?</strong><p>Depending on how you use our Site, your interactions with us, and the permissions you give us, the purposes for which we use your personal data include:</p><p>•    To fulfill your order</p><p>•    To manage and respond to any queries or complaints to our customer service team.</p><p>•    To improve and maintain the Site, and monitor its usage.</p><p>•    For market research, e.g. we may contact you for feedback about our products.</p><p>•    For security purposes, to investigate fraud and where necessary to protect ourselves and third parties.</p><p>•    To comply with our legal and regulatory obligations.</p><p>We rely on the following legal basis, under data protection law, to process your personal data:</p><p>•    Because the processing is necessary to perform a contract with you, or take steps prior to entering into a contract with you (e.g. where you have made a purchase with us, we use your personal data to process the payment and fulfill your order).</p><p>•    Because it is in our legitimate interests as an e-commerce provider to maintain and promote our services. We are always seeking to understand more about our customers in order to offer the best products and customer experience.</p><strong>Who do we share this personal data with?</strong><p>We may share information with governmental agencies or other companies assisting us in fraud prevention or investigation. We may do so when:</p><p>•   Permitted or required by law; or,</p><p> • Trying to protect against or prevent actual or potential fraud or unauthorized transactions; or,</p><p> •  Investigating fraud which has already taken place. The information is not provided to these companies for marketing purposes.</p><p>We may also disclose your personal information, without notice, if such action is necessary to:</p><p>•  Conform to the edicts of the law or comply with legal process served on the Site;</p><p>•  Protect and defend the rights or property of the Site;</p><p>•  Act in urgent circumstances to protect the personal safety of users of the Site.</p><strong>Security</strong><p>This Site ensures that data is encrypted when leaving the Site. This process involves the converting of information or data into a code to prevent unauthorized access. This Site follows this process and employs secure methods to ensure the protection of all payment transactions. Encryption methods such as SSL are utilized to protect customer data when in transit to and from this Site over a secure communications channel.</p><p>Whilst we do everything within our power to ensure that personal data is protected at all times from our Site, we cannot guarantee the security and integrity of the information that has been transmitted to our Site.</p><strong>Cookies</strong><p>The Site may use cookie and tracking technology depending on the features offered. Cookie and tracking technology are useful for gathering information such as browser type and operating system, tracking the number of visitors to the Site, and understanding how visitors use the Site. Cookies can also help customize the Site for visitors. Personal information cannot be collected via cookies and other tracking technology, however, if you previously provided personally identifiable information, cookies may be tied to such information. Aggregate cookie and tracking information may be shared with third parties.</p><strong>Contact Us</strong><p>If you have any questions, concerns, or comments about our privacy policy you may contact us.</p><strong>Disclaimer</strong><p style="color: red;">This site is not a part of the Facebook website or Facebook Inc. Additionally, this site is NOT endorsed by Facebook in any way. FACEBOOK is a trademark of FACEBOOK, Inc.</p>',
    floorPage_1_1: '',
    floorPage_1_2: '',
    floorPage_2Title: 'CONTACT US',
    floorPage_2Flb_1: '24H Online Customer Service:',
    floorPage_2Flb_2: 'Email:',
    floorPage_2Flb_3: 'Questions, comments and requests regarding the website policies are welcomed and should be addressed to',
    floorPage_2Flb_4: '. Please feel free to contact our Customer Care Team for assistance.',
    floorPage_2_1: '',
    floorPage_2_2: '',
    floorPage_2_3: '',
    floorPage_2_4: '',
    floorPage_3Title: 'RETURENS POLICY',
    floorPage_3Html: "<p>Items can only be returned for a refund if they are unopened, unused and in a re-saleable condition with all tamper-resistant seals, packaging and any cellophane intact. You must notify us in writing that you are returning your purchase within 14 days, beginning the day after the day on which you receive the product.</p><p>Please ensure that you also return any free gifts that are associated with your return items or the related order. If the free gift isn't returned, then we reserve the right to deduct the value of the free gift from your refund.</p><p>We recommend a photograph is taken of the item prior to returning it if you are concerned about damage during its return journey.</p><p>Please note that we do not accept returns of personalised products.</p><p><strong>Please note the order number needs to be entered without any letter at the end.</strong> If you do not have your dispatch note or invoice, please include an explanatory note quoting your order number and reason for return.</p><p>Your refund will be processed, once it has been delivered to our warehouse and within 3 working days of arriving back to our us. Refunds can take up to 1 week to show on your account; this is due to the time taken by some banks to process the payment.</p><p>We will refund you by the same payment method used to make the original order (e.g. if you have paid by PayPal, we will reimburse your PayPal account). If you have not received your refund after this time, please contact our<strong> Customer Care Team</strong> and we will be happy assist you.</p><p>Receipt confirmation—Apply for returns/exchanges—Confirmation by customer service-Ship the item back-Delivered to warehouse—Inspection--- Refund/Exchange.</p><p>Please attach with the Order No., Contact No., and Customer name.</p>",
    floorPage_3_1: '',
    floorPage_3_2: '',
    floorPage_4: 'Fleekfly, known as "Strictly Selected Mall", insists on its usual precise attitude for selection of products origin, workmanship and raw materials of all goods adhering to strict criteria including clothing, shoes, bags, houseware, kitchenware and sportswear in order to satisfy our customers with the best products pursuing to the excellent quality.',

    floorPage_aboutus: "A long way walking reveals shoe quality.My grandfather is a shoemaker whose exquisite craftsmanship transcending time and trends. Every time someone came to order, he always asked the customer to take off the shoes and carefully observed the wearing trace.<br/>Everyone\'s walking posture and habit are different, so is the wear on shoes. A good shoemaker can not only measure the actual size, but also find out the difference in walking habits to make a pair of shoes that ingeniously fit.<br/>Good shoes are rare to get. Once used to the effortless comfort, you will always be a paranoid for the shoe selection. Over the years, I have been on the way for over 7,000 kilometers in more than 500 pairs of shoes, out of which I choose the best 8 pairs whose comfort is as unconditionally unique as own wear habits<br/>Searching is never ending and the update selection will never fail you.<br/>Here, may you find one and the only pair!",
    floorPage_shoping: 'Items can only be returned for a refund if they are unopened, unused and in a re-saleable condition with all tamper-resistant seals, packaging and any cellophane intact. You must notify us in writing that you are returning your purchase within 14 days, beginning the day after the day on which you receive the product.<br/>Please ensure that you also return any free gifts that are associated with your return items or the related order. If the free gift isn\'t returned, then we reserve the right to deduct the value of the free gift from your refund.<br/>We recommend a photograph is taken of the item prior to returning it if you are concerned about damage during its return journey.<br/>Please note that we do not accept returns of personalised products.</br>Please note the order number needs to be entered without any letter at the end. If you do not have your dispatch note or invoice, please include an explanatory note quoting your order number and reason for return.<br/>Your refund will be processed, once it has been delivered to our warehouse and within 3 working days of arriving back to our us. Refunds can take up to 1 week to show on your account; this is due to the time taken by some banks to process the payment.<br/>We will refund you by the same payment method used to make the original order (e.g. if you have paid by PayPal, we will reimburse your PayPal account). If you have not received your refund after this time, please contact our Customer Care Team and we will be happy assist you.<br/>',
    floorPage_return: 'Receipt confirmation—Apply for returns/exchanges—Confirmation by customer service-Ship the item back-Delivered to warehouse—Inspection--- Refund/Exchange.<br/>Please attach with the Order No., Contact No., and Customer name.<br/>Items can only be returned for a refund if they are unopened, unused and in a re-saleable condition with all tamper-resistant seals, packaging and any cellophane intact. You must notify us in writing that you are returning your purchase within 14 days, beginning the day after the day on which you receive the product.<br/>Please ensure that you also return any free gifts that are associated with your return items or the related order. If the free gift isn’t returned, then we reserve the right to deduct the value of the free gift from your refund.<br/>We recommend a photograph is taken of the item prior to returning it if you are concerned about damage during its return journey.<br/>Please note that we do not accept returns of personalised products. <br/><b>Please note the order number needs to be entered without any letter at the end. If you do not have your dispatch note or invoice, please include an explanatory note quoting your order number and reason for return.</b><br/>Your refund will be processed, once it has been delivered to our warehouse and within 3 working days of arriving back to our us. Refunds can take up to 1 week to show on your account; this is due to the time taken by some banks to process the payment.<br/>We will refund you by the same payment method used to make the original order (e.g. if you have paid by PayPal, we will reimburse your PayPal account). If you have not received your refund after this time, please contact our <b>customer care team</b> and we will be happy assist you.',
    floorPage_privacy: 'What personal data do we collect about you?<br><br>We collect personal data from you when you provide it to us directly and through your use of the Site. This information may include:<br><br>• Information you provide to us when you use our Site (e.g. your name, contact details, product reviews, and any information which you add our site);<br><br>• Transaction and billing information, if you make any purchases from us or using our Site (e.g. PayPal details and delivery information);<br><br>• Records of your interactions with us (e.g. if you contact our customer service team, interact with us on social media);<br><br>• Information you provide us when you enter a competition or participate in a survey;<br><br>• Information collected automatically, using cookies and other tracking technologies .<br><br>What do we use this personal data for?<br><br>Depending on how you use our Site, your interactions with us, and the permissions you give us, the purposes for which we use your personal data include:<br><br>• To fulfill your order<br><br>• To manage and respond to any queries or complaints to our customer service team.<br><br>• To improve and maintain the Site, and monitor its usage.<br><br>• For market research, e.g. we may contact you for feedback about our products.<br><br>• For security purposes, to investigate fraud and where necessary to protect ourselves and third parties.<br><br>• To comply with our legal and regulatory obligations.<br><br>We rely on the following legal basis, under data protection law, to process your personal data:<br><br>• Because the processing is necessary to perform a contract with you, or take steps prior to entering into a contract with you (e.g. where you have made a purchase with us, we use your personal data to process the payment and fulfill your order).<br><br>• Because it is in our legitimate interests as an e-commerce provider to maintain and promote our services. We are always seeking to understand more about our customers in order to offer the best products and customer experience.<br><br>Who do we share this personal data with?<br><br>We may share information with governmental agencies or other companies assisting us in fraud prevention or investigation. We may do so when:<br><br>• Permitted or required by law; or,<br><br>• Trying to protect against or prevent actual or potential fraud or unauthorized transactions; or,<br><br>• Investigating fraud which has already taken place. The information is not provided to these companies for marketing purposes.<br><br>We may also disclose your personal information, without notice, if such action is necessary to:<br><br>• Conform to the edicts of the law or comply with legal process served on the Site;<br><br>• Protect and defend the rights or property of the Site;<br><br>• Act in urgent circumstances to protect the personal safety of users of the Site.<br><br>Security<br><br>This Site ensures that data is encrypted when leaving the Site. This process involves the converting of information or data into a code to prevent unauthorized access. This Site follows this process and employs secure methods to ensure the protection of all payment transactions. Encryption methods such as SSL are utilized to protect customer data when in transit to and from this Site over a secure communications channel.<br><br>Whilst we do everything within our power to ensure that personal data is protected at all times from our Site, we cannot guarantee the security and integrity of the information that has been transmitted to our Site.<br><br>Cookies<br><br>The Site may use cookie and tracking technology depending on the features offered. Cookie and tracking technology are useful for gathering information such as browser type and operating system, tracking the number of visitors to the Site, and understanding how visitors use the Site. Cookies can also help customize the Site for visitors. Personal information cannot be collected via cookies and other tracking technology, however, if you previously provided personally identifiable information, cookies may be tied to such information. Aggregate cookie and tracking information may be shared with third parties.<br><br>Contact Us<br><br>If you have any questions, concerns, or comments about our privacy policy you may contact us.',
    floorPage_contact_1: '• Email: <b>',
    floorPage_contact_2: '</b> <br/><br/>If you have any question ,please leave a message ,Customer Service will reply generally within 24(workdays)/48(weekends) hours.<br/><br/><br/>For general information, such as buying process, payment methods, delivery options or dispute process, please refer to our Help page.<br/><br/><br/>If you need any inquiries with your recent orders, please contact our Customer Service Center at',
    floorPage_contact_3: '.<br/><br/><br/>Company Address: 152 Beach Road,#14-02, Gateway East, Singapore 189721 (Non-return address, if you need to get the return address, please contact our customer service)<br/><br/><br/>',
    
    mainFooter_1:'Buyer Protection',
    mainFooter_1_1:'Full refund for failure shipping orders.',
    mainFooter_1_2:'Full or Partial refund for not-as-described goods.',
    mainFooter_About:'About Us',
    mainFooter_shipping:'Shipping Terms',
    mainFooter_return:'Return and Exchange Policy',
    mainFooter_privacy:'Privacy Policy',
    mainFooter_contact:'Contact Us',
    mainFooter_2:'. All rights reserved',
    buyNow:'Buy Now',
    seek:'seek',
    searchProducts:'Search products',
    seekErr:'Didn\'t find product results',
    seekErr_1:'Please re-enter product requests!'
}
 function getlang(lang,a){
     if(lang==='ind-BA'){
        return indObj[a] || (function (){console.error('lang_key indObj '+a+' value is undefine!!');return ''})()
     }else{
        return flbObj[a] || (function (){console.error('lang_key flbObj '+a+' value is undefine!!');return ''})()
     }

 }
 function setlang($,lang){
    Array.prototype.forEach.call($("[lang_key]"),function(e) {
        var a = e.getAttribute("lang_key");
        e.textContent = getlang(lang,a)
    });
    Array.prototype.forEach.call($("[lang_key_ph]"),function(e) {
        var a = e.getAttribute("lang_key_ph");
        e.setAttribute('placeholder',getlang(lang,a))
    });
 }
